"""reconfigurei as relations

Revision ID: fa3d5021a221
Revises: 
Create Date: 2020-06-06 01:28:10.130795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3d5021a221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('experiencia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programadorTecnologia',
    sa.Column('id_programador', sa.Integer(), nullable=True),
    sa.Column('id_tecnologia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_programador'], ['programador.id'], ),
    sa.ForeignKeyConstraint(['id_tecnologia'], ['tecnologia.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programadorTecnologia')
    op.drop_table('tecnologia')
    op.drop_table('programador')
    # ### end Alembic commands ###
